# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BleTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BleTest
    
  pod 'SnapKit', '~> 5.0.0'
  pod 'NVActivityIndicatorView'      #动画加载指示
  pod 'AAInfographics', '~> 6.0.0'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'SQLite.swift', '~> 0.12.0'    #数据库框架
  pod 'SwiftyJSON', '~> 4.0'         #JSON解析框架
  pod 'Alamofire', '~> 5.4'          #网络框架

end
